FormulaABD/Models/Risultato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FormulaABD.Models
{
    [Table("Risultati")]
    public class Risultato
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid TracciatoId { get; set; }
        public Guid PilotaId { get; set; }

        [Display(Name = "Tempo")]
        public string TempoGiro { get; set; }

        // Navigations property
        public Pilota Pilota { get; set; }
        public Tracciato Tracciato { get; set; }

        // Valori calcolati
        public int Posizione { get; set; }

        [Display(Name = "Punteggio Posizione")]
        public int PunteggioPosizione { get; set; }

        [Display(Name = "Punteggio Distacco")]
        public int PunteggioDistacco { get; set; }

        [Display(Name = "Totale")]
        public int TotalePunteggioGara { get; set; }
    }
}

FormulaABD/Controllers/RisultatoController.cs
using FormulaABD.DTOs.Risultato;
using FormulaABD.Helpers;
using FormulaABD.Interfaces;
using FormulaABD.Mappers;
using FormulaABD.Models;
using FormulaABD.Repository;
using FormulaABD.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.CompilerServices;

namespace FormulaABD.Controllers
{
    public class RisultatoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RisultatoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        #region GET : Risultato
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] QueryObject query)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Error");
            }

            try
            {
                var risultati = await _unitOfWork.RisultatoRepository.GetAllAsync(query);

                return View(risultati);
            }
            catch (Exception ex)
            {
                return BadRequest($"Errore durante la get dei risultati: {ex.Message}");
            }
        }
        #endregion

        #region GET : Risultato/Details/{guid}
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var risultato = await _unitOfWork.RisultatoRepository.GetByGuidAsync(id);

                return View(risultato);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Si è verificato un errore durante il recupero del risultato: {ex.Message}");
                return View();
            }
        }
        #endregion

        #region POST : Risultato/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var piloti = await _unitOfWork.PilotaRepository.GetAllAsync();
            var tracciati = await _unitOfWork.TracciatoRepository.GetAllAsync();

            var viewModel = new CreateRisultatoVM
            {
                Piloti = piloti.Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                }).ToList(),

                Tracciati = tracciati.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRisultatoVM createRisultatoVM)
        {
            if (!ModelState.IsValid)
            {
                return View(createRisultatoVM);
            }

            try
            {
                await _unitOfWork.BeginTransictionAsync();

                var createdRisultato = await _unitOfWork.RisultatoRepository.CreateAsync(createRisultatoVM.ToRisultato());
                await _unitOfWork.CompleteAsync();

                if (createdRisultato == null)
                {
                    await _unitOfWork.RollbackTransactionAsync();
                    return View("NotFound");
                }

                // Calcolo Punteggi
                var risultati = Funzioni.AggiornaPosizioniEPunteggi(await _unitOfWork.RisultatoRepository.GetAllByTracciatoGuid(createdRisultato.TracciatoId));

                if (risultati == null)
                {
                    await _unitOfWork.RollbackTransactionAsync();
                    return View("Error");
                }

                await _unitOfWork.CompleteAsync();
                await _unitOfWork.CommitTransactionAsync();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Si è verificato un errore durante la creazione del risultato: {ex.Message}");
                return View(createRisultatoVM);
            }
        }
        #endregion

        #region PUT : Risultato/Edit/{guid}
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                await _unitOfWork.BeginTransictionAsync();

                var risulttatoInDb = await _unitOfWork.RisultatoRepository.GetByGuidAsync(id);
                var piloti = await _unitOfWork.PilotaRepository.GetAllAsync();
                var tracciati = await _unitOfWork.TracciatoRepository.GetAllAsync();

                var viewModel = new EditRisultatoVM
                {
                    Id = id,
                    PilotaId = risulttatoInDb.PilotaId,
                    TracciatoId = risulttatoInDb.TracciatoId,
                    TempoGiro = risulttatoInDb.TempoGiro,

                    Piloti = piloti.Select(p => new SelectListItem
                    {
                        Value = p.Id.ToString(),
                        Text = p.Name
                    }).ToList(),

                    Tracciati = tracciati.Select(t => new SelectListItem
                    {
                        Value = t.Id.ToString(),
                        Text = t.Name
                    }).ToList()
                };

                return View(viewModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Si è verificato un errore durante la modifica del risultato: {ex.Message}");
                return View("Error");
            }

        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditRisultatoVM editRisultatoVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit Pilota");
                return View("Edit", editRisultatoVM);
            }

            try
            {
                await _unitOfWork.BeginTransictionAsync();

                var ris = new Risultato
                {
                    Id = editRisultatoVM.Id,
                    PilotaId = editRisultatoVM.PilotaId,
                    TracciatoId = editRisultatoVM.TracciatoId,
                    TempoGiro = editRisultatoVM.TempoGiro!
                };

                // Calcolo Punteggi
                var risultato = await _unitOfWork.RisultatoRepository.UpdateAsync(ris);

                if (risultato == null)
                {
                    await _unitOfWork.RollbackTransactionAsync();
                    return NotFound();
                }

                await _unitOfWork.CompleteAsync();
                await _unitOfWork.CommitTransactionAsync();

                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Si è verificato un errore durante la modifica del risultato: {ex.Message}");
                return View(editRisultatoVM);
            }
        }
        #endregion

        #region DELETE : Risultato/Delete/{guid}
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var risultato = await _unitOfWork.RisultatoRepository.GetByGuidAsync(id);
            if (risultato == null) return View("Error");
            return View(risultato);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteRisultato(Guid id)
        {
            await _unitOfWork.RisultatoRepository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FormulaABD/Views/Risultato/Create.cshtml
@using FormulaABD.ViewModels
@model CreateRisultatoVM
@{
    ViewData["Title"] = "Nuovo Risultato";
}

<h1>Crea Risultato</h1>

<form method="post" asp-action="Create">

    <div class="form-group">
        <label asp-for="PilotaId">Pilota</label>
        <select asp-for="PilotaId" class="form-control" asp-items="Model.Piloti">
            <option value="">-- Seleziona un Pilota --</option>
        </select>
        <span asp-validation-for="PilotaId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TracciatoId">Tracciato</label>
        <select asp-for="TracciatoId" class="form-control" asp-items="Model.Tracciati">
            <option value="">-- Seleziona un Tracciato --</option>
        </select>
        <span asp-validation-for="TracciatoId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TempoGiro">Tempo Giro</label>
        <input asp-for="TempoGiro" class="form-control" placeholder="Enter Tempo Giro">
        <span asp-validation-for="TempoGiro" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary mb-2">Submit</button>
    </div>

</form>

FormulaABD/Views/Risultato/Delete.cshtml
@model Risultato

@{
    ViewData["Title"] = "Delete Risultato";
}

<h1>Sicuro di voler eliminare questo Risultato?</h1>
<div>
    <dl class="row">
        <dt class="col-sm-2">Id</dt>
        <dd class="col-sm-10">@Model.Id</dd>

        <dt class="col-sm-2">Tracciato</dt>
        <dd class="col-sm-10">@Model.Tracciato.Name</dd>

        <dt class="col-sm-2">Pilota</dt>
        <dd class="col-sm-10">@Model.Pilota.Name</dd>

        <dt class="col-sm-2">Giro Migliore</dt>
        <dd class="col-sm-10">@Model.TempoGiro</dd>

        <dt class="col-sm-2">Punti Totali</dt>
        <dd class="col-sm-10">@Model.TotalePunteggioGara</dd>
    </dl>
</div>

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Confirm Delete" class="btn btn-danger float-right mt-3" />
    <a asp-action="Index" class="btn btn-secondary float-left mt-3">Cancel</a>
</form>

FormulaABD/Views/Risultato/Details.cshtml
@model Risultato

@{
    ViewData["Title"] = "Dettaglio Risultato";
}

<h1>Dettagli Risultato</h1>

<div>
    <dl class="row">

        <dt class="col-sm-2">Tracciato</dt>
        <dd class="col-sm-10">@Model.Tracciato.Name</dd>

        <dt class="col-sm-2">Pilota</dt>
        <dd class="col-sm-10">@Model.Pilota.Name</dd>

        <dt class="col-sm-2">Giro Migliore</dt>
        <dd class="col-sm-10">@Model.TempoGiro</dd>

        <dt class="col-sm-2">Punti Totali</dt>
        <dd class="col-sm-10">@Model.TotalePunteggioGara</dd>
    </dl>
</div>

<a asp-controller="Risultato" asp-action="Edit" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Modifica</a>
<a asp-controller="Risultato" asp-action="Delete" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Elimina</a>

FormulaABD/Views/Risultato/Edit.cshtml
@using FormulaABD.ViewModels
@model EditRisultatoVM

@{
    ViewData["Title"] = "Modifica Risultato";
}

<form method="post" asp-action="Edit" enctype="multipart/form-data">

    <input type="hidden" value="Id" id="Id" />

    <div class="form-group">
        <label asp-for="TracciatoId"></label>
        <select asp-for="TracciatoId" class="form-control" asp-items="Model.Tracciati">
            <option value="">-- Seleziona un Tracciato --</option>
        </select>
        <span asp-validation-for="TracciatoId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PilotaId"></label>
        <select asp-for="PilotaId" class="form-control" asp-items="Model.Piloti">
            <option value="">-- Seleziona un Pilota --</option>
        </select>
        <span asp-validation-for="PilotaId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TempoGiro">Tempo Giro</label>
        <input asp-for="TempoGiro" class="form-control" placeholder="Tempo Giro">
        <span asp-validation-for="TempoGiro" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

FormulaABD/Views/Risultato/Index.cshtml
@model IEnumerable<Risultato>
@using System.Collections.Generic;
@using System.Linq;

@{
    ViewData["Title"] = "Risultati";
}

<!-- Intestazione -->
<h1>Risultati</h1>

<!-- Pulsante per la creazione di un nuovo risultato -->
<a asp-controller="Risultato" asp-action="Create" type="button" class="btn btn-sm btn-success">Create</a>

<!-- Sezione di ricerca -->
<section class="mt-3">
    <h2>Cerca Risultati</h2>
    <form asp-action="Index" method="get" class="form-inline">
        <div class="form-group mb-2">
            <input type="text" name="nomeTracciato" class="form-control" placeholder="Cerca..." value="@Context.Request.Query["nomeTracciato"]" />
        </div>
        @* <button type="submit" class="btn btn-primary mb-2 ml-2">Cerca</button> *@
    </form>
</section>

<!-- Tabella dei risultati -->
<table class="table mt-4">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().Id)</th>
            <th>@Html.DisplayNameFor(model => model.First().Tracciato.Name)</th>
            <th>@Html.DisplayNameFor(model => model.First().Pilota.Name)</th>
            <th>@Html.DisplayNameFor(model => model.First().TempoGiro)</th>
            <th>@Html.DisplayNameFor(model => model.First().PunteggioPosizione)</th>
            <th>@Html.DisplayNameFor(model => model.First().PunteggioDistacco)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().TotalePunteggioGara)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Tracciato.Name</td>
                <td>@item.Pilota.Name</td>
                <td>@item.TempoGiro</td>
                <td>@item.PunteggioPosizione</td>
                <td>@item.PunteggioDistacco</td>
                <td>@item.TotalePunteggioGara</td>
                <td>
                    <a asp-controller="Risultato" asp-action="Details" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Dettagli</a>
                </td>
            </tr>
        }
    </tbody>
</table>