FormulaABD/Models/Pilota.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FormulaABD.Models
{
    [Table("Piloti")]
    public class Pilota
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        [Display(Name = "Nome Pilota")]
        public string Name { get; set; } = "";
    }
}

FormulaABD/Controllers/API/PilotaController.cs
using FormulaABD.Data;
using FormulaABD.DTOs.Pilota;
using FormulaABD.Interfaces;
using FormulaABD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FormulaABD.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class PilotaController : Controller
    {
        private readonly IPilotaRepository _pilotaRepo;
        public PilotaController(IPilotaRepository pilotaRepo)
        {
            _pilotaRepo = pilotaRepo;
        }

        #region GET : api/Pilota
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Ok(await _pilotaRepo.GetAllAsync());
        }
        #endregion

        #region GET : api/Pilota/{guid}
        [HttpGet]
        [Route("{guid:Guid}")]
        public async Task<IActionResult> GetbyGuid([FromRoute] Guid guid)
        {
            var pilota = await _pilotaRepo.GetByGuidAsync(guid);

            if (pilota == null)
            {
                return NotFound();
            }

            return Ok(pilota);
        }
        #endregion

        #region POST : api/Pilota
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreatePilotaDto createPilotaDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var newPilota = new Pilota()
            {
                Name = createPilotaDto.Name
            };

            await _pilotaRepo.CreateAsync(newPilota);

            return Ok(newPilota);
        }
        #endregion

        #region DELETE : api/Pilota/{guid}
        [HttpDelete]
        [Route("{guid:Guid}")]
        public async Task<IActionResult> Delete([FromRoute] Guid guid)
        {
            var pilota = await _pilotaRepo.DeleteAsync(guid);

            if (pilota == null)
            {
                return NoContent();
            }

            return Ok(pilota);
        }
        #endregion
    }
}

FormulaABD/Controllers/PilotaController.cs
using FormulaABD.Interfaces;
using FormulaABD.Models;
using FormulaABD.Repository;
using FormulaABD.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FormulaABD.Controllers
{
    public class PilotaController : Controller
    {
        private readonly IPilotaRepository _repository;

        public PilotaController(IPilotaRepository pilotaRepository)
        {
            _repository = pilotaRepository;
        }

        #region GET : Pilota
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var piloti = await _repository.GetAllAsync();
            return View(piloti);
        }
        #endregion

        #region GET : Pilota/Details/{guid}
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var pilota = await _repository.GetByGuidAsync(id);
            if (pilota == null)
            {
                return NotFound();
            }
            return View(pilota);
        }
        #endregion

        #region POST : Pilota/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(CreatePilotaVM createPilotaVM)
        {
            if (!ModelState.IsValid)
            {
                return View(createPilotaVM);
            }

            var pilota = new Pilota
            {
                Name = createPilotaVM.Name
            };

            await _repository.CreateAsync(pilota);

            return RedirectToAction("Index");
        }
        #endregion

        #region PUT : Pilota/Edit/{guid}
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var pilotaInDb = await _repository.GetByGuidAsync(id);

            if (pilotaInDb == null) return View("Error");

            return View(pilotaInDb);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Guid id, EditPilotaVM editPilotaVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit Pilota");
                return View("Edit", editPilotaVM);
            }

            var pilotaInDb = await _repository.GetByGuidAsync(id);

            if (pilotaInDb == null) return View("Error");

            pilotaInDb.Name = editPilotaVM.Name;

            await _repository.UpdateAsync(pilotaInDb);

            return RedirectToAction("Index");
        }
        #endregion

        #region DELETE : Pilota/Delete/{guid}
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var pilota = await _repository.GetByGuidAsync(id);
            if (pilota == null) return View("Error");
            return View(pilota);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePilota(Guid id)
        {
            await _repository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FormulaABD/Views/Pilota/Create.cshtml
@using FormulaABD.ViewModels
@model CreatePilotaVM
@{
    ViewData["Title"] = "Nuovo Pilota";
}

<form method="post" asp-action="Create">

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Enter Pilot Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

FormulaABD/Views/Pilota/Delete.cshtml
@model Pilota
@{
    ViewData["Title"] = "Dettaglio Pilota da Eliminare";
}

<h1>Sicuro di voler eliminare questo pilota?</h1>
<div>
    <dl class="row">
        <dt class="col-sm-2">Id</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        <dt class="col-sm-2">Nome</dt>
        <dd class="col-sm-10">@Model.Name</dd>
    </dl>
</div>

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Confirm Delete" class="btn btn-danger float-right mt-3" />
    <a asp-action="Index" class="btn btn-secondary float-left mt-3">Cancel</a>
</form>

FormulaABD/Views/Pilota/Details.cshtml
@model Pilota

@{
    ViewData["Title"] = "Dettaglio Pilota";
}

<h1>Pilota</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">Id</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        <dt class="col-sm-2">Nome</dt>
        <dd class="col-sm-10">@Model.Name</dd>
    </dl>
</div>

<a asp-controller="Pilota" asp-action="Edit" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Modifica</a>
<a asp-controller="Pilota" asp-action="Delete" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Elimina</a>

FormulaABD/Views/Pilota/Edit.cshtml
@model Pilota

@{
    ViewData["Title"] = "Edit Pilota";
}

<form method="post" asp-action="Edit" enctype="multipart/form-data">

    <input type="hidden" value="Id" id="Id" />

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

FormulaABD/Views/Pilota/Index.cshtml
@model IEnumerable<Pilota>

@{
    ViewData["Title"] = "Piloti";
}

<h1>Piloti</h1>
<a asp-controller="Pilota" asp-action="Create" type="button" class="btn btn-sm btn-success">Create</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    <a asp-controller="Pilota" asp-action="Details" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Dettagli</a>
                </td>
            </tr>
        }
    </tbody>
</table>