FormulaABD/Models/Tracciato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FormulaABD.Models
{
    [Table("Tracciati")]
    public class Tracciato
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        [Display(Name = "Nome Tracciato")]
        public string Name { get; set; } = "";
    }
}

FormulaABD/Controllers/API/TracciatoController.cs
using FormulaABD.DTOs.Tracciato;
using FormulaABD.Interfaces;
using FormulaABD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

namespace FormulaABD.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class TracciatoController : ControllerBase
    {
        private readonly ITracciatoRepository _tracciatoRepo;

        public TracciatoController(ITracciatoRepository tracciatoRepo)
        {
            _tracciatoRepo = tracciatoRepo;
        }

        #region GET : api/Tracciato
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Ok(await _tracciatoRepo.GetAllAsync());
        }
        #endregion

        #region GET : api/Tracciato/{guid}
        [HttpGet]
        [Route("{guid:Guid}")]
        public async Task<IActionResult> GetByGuid([FromRoute] Guid guid)
        {
            var tracciato = await _tracciatoRepo.GetByGuidAsync(guid);

            if (tracciato == null)
            {
                return NotFound();
            }

            return Ok(tracciato);
        }
        #endregion

        #region POST : api/Tracciato
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreateTracciatoDto createTracciatoDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var nuovoTracciato = new Tracciato()
            {
                Name = createTracciatoDto.Name
            };

            await _tracciatoRepo.CreateAsync(nuovoTracciato);

            return CreatedAtAction(nameof(GetAll), nuovoTracciato);
        }
        #endregion

        #region DELETE : api/Tracciato
        [HttpDelete]
        [Route("{guid:Guid}")]
        public async Task<IActionResult> Delete([FromRoute] Guid guid)
        {
            var tracciato = await _tracciatoRepo.RemoveAsync(guid);

            if (tracciato == null)
            {
                return NoContent();
            }

            return Ok(tracciato);
        }
        #endregion
    }
}

FormulaABD/Controllers/TracciatoController.cs
using FormulaABD.Interfaces;
using FormulaABD.Models;
using FormulaABD.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FormulaABD.Controllers
{
    public class TracciatoController : Controller
    {
        private readonly ITracciatoRepository _repository;

        public TracciatoController(ITracciatoRepository repository)
        {
            _repository = repository;
        }

        #region GET : Tracciato
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var tracciati = await _repository.GetAllAsync();
            return View(tracciati);
        }
        #endregion

        #region GET : Tracciato/{guid}
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var tracciato = await _repository.GetByGuidAsync(id);
            if (tracciato == null) 
            {
                return NotFound();
            }
            return View(tracciato);
        }
        #endregion

        #region POST : Tracciato/Create/{guid}
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTracciatoVM createTracciatoVM)
        {
            if (!ModelState.IsValid)
            {
                return View(createTracciatoVM);
            }

            var tracciato = new Tracciato
            {
                Name = createTracciatoVM.Name
            };

            await _repository.CreateAsync(tracciato);
            return RedirectToAction("Index");
        }
        #endregion

        #region PUT : Tracciato/Edit/{guid}
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tracciato = await _repository.GetByGuidAsync(id);

            if (tracciato == null) return View("Error");

            return View(tracciato);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Guid id, EditPilotaVM editPilotaVM)
        {
            if (!ModelState.IsValid) 
            {
                ModelState.AddModelError("", "Failed to edit Tracciato");
                return View("Edit", editPilotaVM);
            }

            var tracciatoInDb = await _repository.GetByGuidAsync(id);
            
            if (tracciatoInDb == null) return View("Error");

            tracciatoInDb.Name = editPilotaVM.Name;

            await _repository.UpdateAsync(tracciatoInDb);

            return RedirectToAction("Index");
        }
        #endregion

        #region DELETE : Tracciato/Delete/{guid}
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var tracciato = await _repository.GetByGuidAsync(id);
            if (tracciato == null) return NotFound();
            return View(tracciato);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteTracciato(Guid id)
        {
            await _repository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FormulaABD/Views/Tracciato/Create.cshtml
@using FormulaABD.ViewModels
@model CreatePilotaVM
@{
    ViewData["Title"] = "Nuovo Tracciato";
}

<form method="post" asp-action="Create">

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Enter Track Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

FormulaABD/Views/Tracciato/Delete.cshtml
@model Tracciato

@{
    ViewData["Title"] = "Delete Tracciato";
}

<h1>Sei sicuro di voler eliminare questo tracciato?</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">Id</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        <dt class="col-sm-2">Nome</dt>
        <dd class="col-sm-10">@Model.Name</dd>
    </dl>
</div>

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Confirm Delete" class="btn btn-danger float-right mt-3" />
    <a asp-action="Index" class="btn btn-secondary float-left mt-3">Cancel</a>
</form>

FormulaABD/Views/Tracciato/Details.cshtml
@model Tracciato

@{
    ViewData["Title"] = "Dettaglio Tracciato";
}

<h1>Tracciato</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">Id</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        <dt class="col-sm-2">Nome</dt>
        <dd class="col-sm-10">@Model.Name</dd>
    </dl>
</div>

<a asp-controller="Tracciato" asp-action="Edit" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Modifica</a>
<a asp-controller="Tracciato" asp-action="Delete" asp-route-id="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">Elimina</a>

FormulaABD/Views/Tracciato/Edit.cshtml
@model Tracciato

@{
    ViewData["Title"] = "Edit Tracciato";
}

<form method="post" asp-action="Edit" enctype="multipart/form-data">

    <input type="hidden" value="Id" id="Id" />

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

FormulaABD/Views/Tracciato/Index.cshtml
@model IEnumerable<Tracciato>

@{
    ViewData["Title"] = "Tracciati";
}

<h1>Tracciati</h1>
<a asp-controller="Tracciato" asp-action="Create" type="button" class="btn btn-sm btn-success">Create</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    <a asp-controller="Tracciato" asp-action="Details" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Dettagli</a>
                </td>
            </tr>
        }
    </tbody>
</table>